services:
  mimir:
    image: grafana/mimir:2.14.3
    command: -config.file=/etc/mimir/config.yaml
    volumes:
      - ./configs/mimir.yaml:/etc/mimir/config.yaml
      - ./docker/data/mimir:/data/mimir
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.4.2
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./configs/loki.yaml:/etc/loki/config.yaml
      - ./docker/data/loki:/loki
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:main-d635daa
    command: -config.file=/etc/tempo/config.yaml
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/config.yaml
      - ./docker/data/tempo:/data/tempo
    ports:
      - "3200:3200"  # Tempo's query port
      - "4317" # otlp grpc
      - "4318" # otlp http

  pyroscope:
    image: grafana/pyroscope:1.12.0
    ports:
      - "4040:4040"
    volumes:
      - ./docker/data/pyroscope:/data/pyroscope

  alloy:
    image: grafana/alloy:v1.7.1
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
    volumes:
      - ./configs/alloy.alloy:/etc/alloy/config.alloy
      - ./docker/data/alloy/data:/var/lib/alloy/data
    ports:
      - "4317:4317"   # OTLP/gRPC telemetry data (metrics, logs, traces, profiling) receiver port
      - "4318:4318"   # OTLP/HTTP telemetry data (metrics, logs, traces, profiling) receiver port 
      - "12345:12345" # Alloy web interface
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "13000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080" 
    volumes:
      - ./configs:/app/configs
    environment:
      - CONFIG_FILE=/app/configs/api/docker.yml
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
      - alloy

volumes:
  grafana-storage:
