{
 "title": "Mimir Metrics Dashboard",
 "tags": [
  "mimir",
  "metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success Request Rate by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{job=\"go-service\", status=\"success\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Request Rate by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path, status) (rate(http_requests_total{job=\"go-service\", status!=\"success\"}[5s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"go-service\", status!=\"success\"}[5m])) / sum(rate(http_requests_total{job=\"go-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Distribution by Path",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{job=\"go-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}